export const applyDiscountToggle = '#block-discount-heading'
export const discountCodeField = '#discount-code'
export const applyDiscountBtn = '#discount-form > .actions-toolbar > .primary > .action'
export const alertInvalidDiscountCode = '.messages > .message' 
export const placeOrderBtn = '.payment-method-content > :nth-child(4) > div.primary > .action'